[features]
seeds = false
skip-lint = false
[programs.localnet]
nft_vault = "cEQiCRrQzkEVHTPrTtNy6sPTkJRWF5KLdUeritG2xB6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/sudhan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
